options {
    directory "/var/cache/bind";

    // Open resolver — acepta consultas de cualquier origen
    // Vulnerable a amplificacion DNS y flood (intencionalmente inseguro - lab academico)
    allow-query     { any; };
    allow-recursion { any; };
    allow-query-cache { any; };

    // Rate limiting desactivado — vulnerable a UDP flood
    // rate-limit { responses-per-second 5; };

    dnssec-validation no;
    recursion yes;

    listen-on   { any; };
    listen-on-v6 { none; };
};

zone "lab.local" {
    type master;
    file "/etc/bind/db.lab.local";
};

zone "20.172.in-addr.arpa" {
    type master;
    file "/etc/bind/db.172.20";
};
